services:
  wordpress:
    build:
      dockerfile: config/Dockerfile
      context: .
      args:
        HOST_USER_NAME: ${HOST_USER_NAME}
        HOST_USER_ID: ${HOST_USER_ID}
        HOST_GROUP_NAME: ${HOST_GROUP_NAME}
        HOST_GROUP_ID: ${HOST_GROUP_ID}
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: dbuser
      WORDPRESS_DB_PASSWORD: dbpassword
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: '1'
      APACHE_RUN_USER: ${HOST_USER_NAME}
      APACHE_RUN_GROUP: ${HOST_GROUP_NAME}
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: dbpassword
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 9999:8080
    depends_on:
      - db

volumes:
  db: