services:
  wordpress:
    build: ./config
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: dbuser
      WORDPRESS_DB_PASSWORD: dbpassword
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: '1'
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: dbpassword
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 9999:8080
    depends_on:
      - db

volumes:
  db: